name: Build and Deploy Documentation

# Автоматическая сборка при push в main/master
on:
  push:
    branches: [ main, master ]
  
  # Возможность запуска вручную
  workflow_dispatch:

# Права доступа для записи в Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Предотвращение одновременного выполнения деплоев
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Сборка документации
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt
    
    - name: Build documentation
      run: |
        cd source
        make html
        # Создаем .nojekyll для правильной работы с GitHub Pages
        touch _build/html/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./source/_build/html
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy documentation ${{ github.sha }}'

  # Проверка ссылок (опционально)
  link-check:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Wait for deployment
      run: sleep 60
      
    - name: Check links
      uses: untitaker/hyperlink@0.1.32
      with:
        args: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
      continue-on-error: true 