name: Build & Deploy Sphinx docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:          # ⬅︎ нужны действиям, которые пушат
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Клон репозитория
      - uses: actions/checkout@v4

      # 2. Python ≥ 3.11 (нужен Sphinx 8+)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Установка зависимостей (тут же и sphinx_design)
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Сборка HTML; Makefile сам знает, что исходники в source/, а build/ – вывод
      - name: Build HTML
        run: make html

      # 5. Публикация содержимого build/html в ветку gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages          # цель
          publish_dir: build/html           # откуда брать собранный сайт 